services:

  db:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: secret
  
  adminer: 
    image: adminer
    restart: always
    ports:
      - 8080:8080

